# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(393, 424)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(10, 9, 271, 44))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setStyleSheet("background-color: rgb(200, 214, 228);\n"
"color: rgb(255, 255, 255);")
        self.result.setObjectName("result")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setEnabled(True)
        self.btn_0.setGeometry(QtCore.QRect(0, 360, 150, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0.sizePolicy().hasHeightForWidth())
        self.btn_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_0.setFont(font)
        self.btn_0.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_0.setObjectName("btn_0")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(0, 60, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(100, 60, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(200, 60, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_9.setObjectName("btn_9")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(0, 160, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(100, 160, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(200, 160, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_6.setObjectName("btn_6")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(0, 260, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(100, 260, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(200, 260, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btn_3.setObjectName("btn_3")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(300, 60, 91, 90))
        self.btn_plus.setMinimumSize(QtCore.QSize(91, 90))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_plus.setFont(font)
        self.btn_plus.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(300, 150, 91, 90))
        self.btn_minus.setMinimumSize(QtCore.QSize(91, 90))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_minus.setFont(font)
        self.btn_minus.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(300, 240, 91, 90))
        self.btn_div.setMinimumSize(QtCore.QSize(91, 90))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_div.setFont(font)
        self.btn_div.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.btn_div.setObjectName("btn_div")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(300, 330, 91, 90))
        self.btn_mult.setMinimumSize(QtCore.QSize(91, 90))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_mult.setFont(font)
        self.btn_mult.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.btn_mult.setObjectName("btn_mult")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setGeometry(QtCore.QRect(150, 360, 150, 60))
        self.btn_equal.setMinimumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_equal.setFont(font)
        self.btn_equal.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.btn_equal.setObjectName("btn_equal")
        self.touch_btn = QtWidgets.QPushButton(self.centralwidget)
        self.touch_btn.setGeometry(QtCore.QRect(281, 9, 111, 44))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(13)
        self.touch_btn.setFont(font)
        self.touch_btn.setAutoFillBackground(False)
        self.touch_btn.setStyleSheet("background-color: rgb(172, 99, 255);")
        self.touch_btn.setCheckable(False)
        self.touch_btn.setObjectName("touch_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.result.setText(_translate("MainWindow", "0"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_div.setText(_translate("MainWindow", "/"))
        self.btn_mult.setText(_translate("MainWindow", "*"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.touch_btn.setText(_translate("MainWindow", "Тицни мене"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

